### ISSUE TITLE
v4/records/{id}/workflowTasks does not return any content

### ISSUE THREAD

**Issue by mmartin78** [Accela-Inc/developer-forum#37]
v4/records/{id}/workflowTasks return 200 OK, but never return the tasks for the record.

Example:

GET https://apis.accela.com/v4/records/ISLANDTON-14CAP-00000-0008M/workflowTasks HTTP/1.1
Content-Type: application/json
Accept: application/json
x-accela-appid: <appid>
x-accela-agency: islandton
x-accela-environment: TEST
Authorization: <token>
Host: apis.accela.com

HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 14
Content-Type: application/json
Expires: -1
Server: Microsoft-IIS/8.5
Server: Microsoft-IIS/7.5
Server: unknow
x-accela-resp-gateway-version: 3.1.0.1
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
x-accela-traceId: 141027185749429-313e3b76
X-Powered-By: ASP.NET
Date: Mon, 27 Oct 2014 18:57:49 GMT
Connection: close

{"status":200}

**Comment by mmartin78** [comment]
@axtheset any new findings on this?

**Comment by axtheset** [comment]
Finally got this confirmed as a bug, the resolution is under development and will be delivered in an upcoming hotfix early March.

**Comment by mmartin78** [comment]
Thanks @axtheset. We really need this one, good to hear.
