### ISSUE TITLE
How to search for records in same address as a record?

### ISSUE THREAD

**Issue by mmartin78** [Accela-Inc/developer-forum#43]
I am trying to search for records in the same address as a record I have already retrieved, but I must be doing something wrong since I get a few records with no address as the response. Below are my requests:

Get my main record (**this is fine**).

Request:
POST https://apis.accela.com/v4/search/records?offset=-1&limit=-1&expand=addresses HTTP/1.1

{"customId":"BLD14-00100"}

Response:
{"result":[{"addresses":[{"streetStart":1,"refAddressId":**16830**,"id":**1000619244**,"serviceProviderCode":"ISLANDTON","isPrimary":"Y","streetName":"ALLEGHENY","city":"PETALUMA","postalCode":"94952","recordId":{"id":"ISLANDTON-14CAP-00000-0008M","serviceProviderCode":"ISLANDTON","trackingId":0,"value":"14CAP-00000-0008M"},"country":{"value":"US","text":"United States"},"status":{"value":"A","text":"Active"},"state":{"value":"CA","text":"CA"},"streetSuffix":{"value":"CT","text":"CT"}}],
...

Now, I try to get my related records for same address, tried a few things but it is not working.. (see **bold**, what is the right way to pull records by address id?):

POST https://apis.accela.com/v4/search/records?offset=-1&limit=-1 HTTP/1.1

{"modules":["Building"],"openedDateFrom":"2014-07-25 00:00:00","address":{"id":**1000619244**,"refAddressId":**16830**}}

**Comment by mheadd** [comment]
@mmartin78 Quick update - the API is currently investigating this issue. Will update as soon as I have more info.

**Comment by mheadd** [comment]
@mmartin78 The API team reports that searching by address id is not supported. I'll make sure that this is reflected in the documentation.

For reference, [these fields](https://gist.github.com/mheadd/a5a57d74f382a70c15fb) are supported in the <code>/search</code> method call.

Hope this helps - let me know if you have any additional questions.
