### ISSUE TITLE
Getting Drilldown Settings function not working

### ISSUE THREAD

**Issue by yaseentt** [Accela-Inc/developer-forum#45]
I'm trying to use the Drilldown settings function:

https://developer.accela.com/docs/api_reference/v4.get.settings.drillDowns.drillId.html

I'm trying to use it as follows:

GET /v4/settings/drillDowns/62?parentValue=Species

Where 62 is the drillId and parentValue is the field id.

I get the following output:

{
"status": 404,
"code": "resource_not_found",
"message": "Not Found(The requested resource could not be found).",
"more": "java.lang.Exception: 404\ \ \	at com.accela.restapis.framework.jaxrs.interceptors.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:114)\ \ \	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:236)\ \ \	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:89)\ \ \	at org.apache.cxf.transport.servlet.ServletDestination.invoke(ServletDestination.java:99)\ \ \	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:337)\ \ \	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:145)\ \ \	at org.apache.cxf.transport.servlet.AbstractCXFServlet.invoke(AbstractCXFServlet.java:163)\ \ \	at org.apache.cxf.transport.servlet.AbstractCXFServlet.doGet(AbstractCXFServlet.java:145)\ \ \	at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)\ \ \	at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\ \ \	at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\ \ \	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)\ \ \	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)\ \ \	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:182)\ \ \	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:84)\ \ \	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)\ \ \	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)\ \ \	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:157)\ \ \	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)\ \ \	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)\ \ \	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)\ \ \	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:879)\ \ \	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:617)\ \ \	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1754)\ \ \	at java.lang.Thread.run(Thread.java:722)\ \ "
}

Thanks

**Comment by axtheset** [comment]
@yaseentt, recent response from our API engineering team is requesting the version of AA your are using, 7.3.2 or 7.3.3?  Thanks!

**Comment by yaseentt** [comment]
@axtheset I'm using AA 7.3.3.1

Thanks!

**Comment by yaseentt** [comment]
@axtheset am I using this function correctly btw? What does the parentValue refer to?

**Comment by axtheset** [comment]
Thanks for the version number, it does appear you are using the request correctly, the API team is checking the code to determine what would return that response.

**Comment by yaseentt** [comment]
@axtheset Thanks a lot, looking forward to hear back in regards of this issue.
