### ISSUE TITLE
AGENCY LOCATE

### ISSUE THREAD

**Issue by carterreece** [Accela-Inc/developer-forum#46]
Can anyone help find a specific AGENCY? I see it in the URL from their site but it does not show in the v4 agencies list. Thoughts of where to start?

Agency GWINNETT
Sample URL: https://eddspermits.gwinnettcounty.com/CitizenAccess/Cap/CapDetail.aspx?Module=Building&TabName=Building&capID1=14BLD&capID2=00000&capID3=11035&agencyCode=GWINNETT&IsToShowInspection=

**Comment by mheadd** [comment]
You're looking for the agency name so that you can make API calls against that agency's data, correct?

**Comment by carterreece** [comment]
Yes, thats correct. Just getting ALL RECORDS. We've been successful with
ATLANTA_GA but now looking to surrounding agencies and not seeing them and
curious as to what we're missing.

On Thu, Jan 1, 2015 at 2:04 PM, Mark Headd <notifications@github.com> wrote:

> You're looking for the agency name so that you can make API calls against
> that agency's data, correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Accela-Inc/developer-forum/issues/46#issuecomment-68494877>
> .
>



-- 
*Reece Carter*
www.studio3v.com
m 404.788.0265

o 404.939.4738
f 404.939.0912

"We Are Virtually Validating Your Vision"

Disclaimer: Reece Carter, Designed and Studio 3V, LLC are a design firm
specializing in Architectural Environments, 3d Visualization, and space
planning for residential design. Reece Carter, Designed and Studio 3V, LLC
collaborate with design professionals as they are required. There are no
registered architects within this firm.

**Comment by axtheset** [comment]
It appears that Gwinnet County has not exposed their platform via API quite yet.  There are a few setup items an agency must work with us on to expose the API for their installation.  They may have chosen not to do that quite yet.

**Comment by carterreece** [comment]
Thanks, Seth, for the input. I am reaching out to the architect for
Gwinnett today. thx. reece

On Fri, Jan 2, 2015 at 8:29 AM, Seth Axthelm <notifications@github.com>
wrote:

> It appears that Gwinnet County has not exposed their platform via API
> quite yet. There are a few setup items an agency must work with us on to
> expose the API for their installation. They may have chosen not to do that
> quite yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Accela-Inc/developer-forum/issues/46#issuecomment-68526532>
> .
>



-- 
*Reece Carter*
www.studio3v.com
m 404.788.0265

o 404.939.4738
f 404.939.0912

"We Are Virtually Validating Your Vision"

Disclaimer: Reece Carter, Designed and Studio 3V, LLC are a design firm
specializing in Architectural Environments, 3d Visualization, and space
planning for residential design. Reece Carter, Designed and Studio 3V, LLC
collaborate with design professionals as they are required. There are no
registered architects within this firm.

**Comment by axtheset** [comment]
Great, please feel free to put them in contact with us as well if they have any questions.  developers@accela.com.

**Comment by carterreece** [comment]
Look for JOhn Cross to be in touch ASAP. Thx!

**Comment by carterreece** [comment]
@axtheset this case raises another question for us; is there a master list of Agencys that we can reach out to ask the same question we posed to Gwinnett in that of getting involved in the basic level of openness?

**Comment by axtheset** [comment]
Gwinnett dropped me a line and I pointed them down the path to get started.  They are on a version of our platform from earlier this year, you will need to use [version 3 of the Construct API](https://developer.accela.com/Resource/ApisAbout) once they have opened up the API.

As for listing agencies that are open you can refer to this API: https://developer.accela.com/docs/api_reference/v4.get.agencies.html
