### ISSUE TITLE
Calling EMSE script from REST APIs, how to pass a parameter

### ISSUE THREAD

**Issue by yaseentt** [Accela-Inc/developer-forum#48]
I'm using the following REST function:

POST /v4/scripts/SCRIPT_NAME?sampleParameter=Value

I have created an EMSE script called SCRIPT_NAME that contains:

var sampleParameter = aa.env.getValue("sampleParameter");
aa.env.setValue("The Output", "Sample Parameter Value is: " + sampleParameter);

When I call this script from REST API I'm getting the output without my sample parameter, I have tried passing it through the request body in the JSON syntax but that didn't work either. Is there a way to pass parameters to my custom script?

**Comment by axtheset** [comment]
Try passing in as a post body instead of a query string.

**Comment by yaseentt** [comment]
@axtheset this works, thanks a lot!
