### ISSUE TITLE
Clarification on inspection status

### ISSUE THREAD

**Issue by mmartin78** [Accela-Inc/developer-forum#50]
We are trying to pull all inspections that have issues that need to be resolved. Our strategy is to pull inspections for a record and look at the status to determine if we need to go further and pull the issues for that inspection. Two questions below:

1. How do we know which statuses correspond to inspections that have issues to be resolved? What is the difference between resultType and result below?
{
"displayOrder": 1,
"resultType": "APPROVED",
"group": "BLD_STANDARD",
"result": {
"value": "Passed",
"text": "Passed"
}

2. After we determine that an inspection has issues, what should we look at to pull the issues comments, checklists, conditions or all of them?

**Comment by axtheset** [comment]
1.  The result object will the the status that the inspector has submitted.  This is configurable by inspection type but will mostly be consistent across many inspection types.  resultType is a system field and can only have the values of APPROVED, PENDING and DENIED.  The end user does not see the resultType, it dictates some system behavior.  For example, PENDING will keep the inspection open allowing it to be resulted at a later date.

2. There are a handful of places to look.  First option is in [inspection comments](https://developer.accela.com/docs/api_reference/v4.get.inspections.inspectionId.comments.html), many times this is where any issues may be documented in this text area field.  The next option for more details inspections will be in checklists and checklist items:
[Checklists](https://developer.accela.com/docs/api_reference/index.html#Inspections/Checklists)
[Checklist Items](https://developer.accela.com/docs/api_reference/index.html#Inspections/Checklists/ChecklistItems)
[Checklist Items Custom Forms](https://developer.accela.com/docs/api_reference/index.html#Inspections/Checklists/ChecklistItems/CustomForms)
[Checklist Item Tables](https://developer.accela.com/docs/api_reference/index.html#Inspections/Checklists/ChecklistItems/CustomTables)
[Checklist Item Documents](https://developer.accela.com/docs/api_reference/index.html#Inspections/Checklists/ChecklistItems/Documents)

There are a couple of other items associated to inspections as well, here is the listing of all of them: https://developer.accela.com/docs/api_reference/index.html#Inspections

**Comment by mmartin78** [comment]
1. So I assume just looking at (resultType = DENIED) will tell me if there are issues that the applicant has to resolve or could there be other cases?

2. checklistStatus will this tell if there are issues with that checklist and then I need to look at the items? is this user configurable?

**Comment by axtheset** [comment]
1.) Typically that will be the case combined with comments, checklists or even conditions.  Doesn't mean a customer couldn't have APPROVED configured as a result type for a failed inspection status.

2.) You'll typically need to look at the checklist items and each status.  This is very flexible and configurable.

**Comment by mmartin78** [comment]
Ok thanks, I got it. Couple more questions on inspection workflow :)

1. Let say an inspection is DENIED, can it be APPROVED at a later time? or will a new inspection be created to recheck the same items?

2. Do you keep a history of checklist item status changes at all? or is the history only for the whole inspection status?

**Comment by axtheset** [comment]
1.) A new inspection will be created.  There is a feature of the platform that will carry over failed checklist items over to the new inspection so inspector can be aware of previously failed items.

2.) There is a checklist history but it appears not exposed to the API at this time.

**Comment by mmartin78** [comment]
For number 1 above. Can this relationship between the two inspections be identified somehow through the API? is that what /v4/inspections/{inspectionIds}/histories shows?
