### ISSUE TITLE
Error message "SubGroup :GENERAL,field :Breed Can not found custom form setting on request record." when trying to update record ASI

### ISSUE THREAD

**Issue by yaseentt** [Accela-Inc/developer-forum#51]
I'm creating a partial record and then updating its ASI using record update method, when I update the ASI I'm getting the following error:

"message": " SubGroup :GENERAL,field :Breed Can not found custom form setting on request record.\r\n"

My Request:

POST /v4/records/DMEP-14EST-00000-02914/customForms?

[
	{
		"id": "PHS_SACO-GENERAL",
		"Breed": "Cat"
	}
]

I double checked my record type ASI group to make sure its spelled correctly and that the field Breed does in fact exist, I also used the same method on a different record type which had identical ASI fields and it worked fine.

I suspect it's something in the configuration but I can't seem to figure it out, any help is appreciated thanks!

**Comment by axtheset** [comment]
That is interesting, could you use this request and see what the response is?

GET /v4/settings/records/types/{id}/customForms

where the id is the record type id

**Comment by yaseentt** [comment]
@axtheset This is part of the output I'm getting:

{
   "id": "PHS_SACO-GENERAL",
   "text": "GENERAL",
   "displayOrder": 20,
   "fields": [ 
   {
      "id": "Breed",
      "text": "Breed",
      "isReadonly": "N",
      "fieldType": "DropdownList",
      "maxLength": 0,
      "isRequired": "Y",
      "drillDown": {
         "isRoot": false
      }
   }
   ]
}

**Comment by axtheset** [comment]
That is very strange, you may want to check the av.biz server.log and see if it provides anymore details on that error.

**Comment by yaseentt** [comment]
@axtheset I toggled the ACA displayable to NO then back to YES and cleared cache and it worked fine, thanks for your help!
