### ISSUE TITLE
/v4/inspections/{inspectionId}/checklists does not return items

### ISSUE THREAD

**Issue by mmartin78** [Accela-Inc/developer-forum#52]
We are invoking: https://apis.accela.com/v4/inspections/4230559/checklists on the islandton test bed

Both checklists returned have items that show up on AA, but don't return anything from API. Also missing **checklistStatus** field. Is this a bug or documentation bug?

We get the following back:

{
"result": [
{
"serviceProviderCode": "ISLANDTON",
"entityType": "INSPECTION",
"inspectionId": "4230559",
"id": 2836047,
"recordId": {
"id": "ISLANDTON-13CAP-00000-000NT",
"serviceProviderCode": "ISLANDTON",
"trackingId": 0,
"value": "13CAP-00000-000NT"
},
"guideType": {
"value": "BLD_GS1",
"text": "BLD_GS1"
}
},
{
"serviceProviderCode": "ISLANDTON",
"entityType": "INSPECTION",
"inspectionId": "4230559",
"id": 2836048,
"recordId": {
"id": "ISLANDTON-13CAP-00000-000NT",
"serviceProviderCode": "ISLANDTON",
"trackingId": 0,
"value": "13CAP-00000-000NT"
},
"guideType": {
"value": "Electrical",
"text": "Electrical"
}
}
],
"status": 200
}

**Comment by axtheset** [comment]
This is a documentation issue that will be resolved.  We have submitted the request to product management to review as an enhancement.
