### ISSUE TITLE
Creating Record Document and specifying group and category is not working

### ISSUE THREAD

**Issue by yaseentt** [Accela-Inc/developer-forum#53]
I'm trying to create a record document with a specific group and category but I'm getting an exception as follows:

Request:

POST v4/records/DMEP-15PHS-00000-00341/documents?
Content-type: multipart/form-data; charset=ISO-8859-1; boundary=-------------------------acebdf13572468

Request body:

---------------------------acebdf13572468
Content-Disposition: form-data; name="uploadedFile"; filename="123456.txt"
Content-Type: text/plain

Some Text Content here
---------------------------acebdf13572468
Content-Disposition: form-data; name="fileInfo"

[
   {
       "fileName": "123456.txt",
       "fileType": "text/plain",
       "group": "PHS",
	"category": "Animal Photo",
       "description": "upload testing....."
   }
]
---------------------------acebdf13572468--

Output:

{
"status": 500,
"code": 1005,
"message": "We are experiencing internal server error. Please contact Agency Administrator for assistance.",
"more": "com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class com.accela.i18n.IdentifierModel] from String value; no single-String constructor/factory method (through reference chain: com.accela.aa.ads.ads.DocumentModel[\"i18NDocGroup\"])\ \ \	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createFromStringFallbacks(StdValueInstantiator.java:422)\ \ \	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:298)\ \ \	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromString(BeanDeserializer.java:424)\ \ \	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:129)\ \ \	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)\ \ \	at com.accela.json.impl.CustomJsonDeserializer.beanDeserializeAndSet(CustomJsonDeserializer.java:172)\ \ \	at com.accela.json.impl.CustomJsonDeserializer.customDeserializeAndSet(CustomJsonDeserializer.java:232)\ \ \	at com.accela.json.impl.CustomJsonDeserializer.parseAndSet(CustomJsonDeserializer.java:155)\ \ \	at com.accela.json.impl.CustomJsonDeserializer.deserializeFromObject(CustomJsonDeserializer.java:98)\ \ \	at com.accela.json.impl.CustomObjectMapper.readObjectOrArray(CustomObjectMapper.java:111)\ \ \	at com.accela.json.impl.CustomObjectMapper._readValue(CustomObjectMapper.java:86)\ \ \	at com.accela.json.impl.CustomObjectMapper.readValue(CustomObjectMapper.java:49)\ \ \	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1285)\ \ \	at com.accela.restapis.framework.jaxrs.providers.JSONProvider.toModel(JSONProvider.java:225)\ \ \	at com.accela.restapis.document.util.DocumentUtil.getFileInfoJsonSchema(DocumentUtil.java:124)\ \ \	at com.accela.restapis.document.RecordDocumentResourceV1.uploadDocumentForRecordV1(RecordDocumentResourceV1.java:175)\ \ \	at sun.reflect.GeneratedMethodAccessor3013.invoke(Unknown Source)\ \ \	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\ \ \	at java.lang.reflect.Method.invoke(Method.java:601)\ \ \	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:166)\ \ \	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:82)\ \ \	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:122)\ \ \	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:70)\ \ \	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:57)\ \ \	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)\ \ \	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)\ \ \	at java.util.concurrent.FutureTask.run(FutureTask.java:166)\ \ \	at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)\ \ \	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:95)\ \ \	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:236)\ \ \	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:89)\ \ \	at org.apache.cxf.transport.servlet.ServletDestination.invoke(ServletDestination.java:99)\ \ \	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:337)\ \ \	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:145)\ \ \	at org.apache.cxf.transport.servlet.AbstractCXFServlet.invoke(AbstractCXFServlet.java:163)\ \ \	at org.apache.cxf.transport.servlet.AbstractCXFServlet.doPost(AbstractCXFServlet.java:141)\ \ \	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)\ \ \	at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\ \ \	at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)\ \ \	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\ \ \	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)\ \ \	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)\ \ \	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:182)\ \ \	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:84)\ \ \	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)\ \ \	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)\ \ \	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:157)\ \ \	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)\ \ \	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)\ \ \	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)\ \ \	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:879)\ \ \	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:617)\ \ \	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1754)\ \ \	at java.lang.Thread.run(Thread.java:722)\ \ ",
"traceId": "rest-8659"
}

However if I remove group and category from the JSON body the request works fine, I checked that the group and category does in fact exist and are assigned to this record type, I also verified the category id value by using v4/settings/documents/categories to get a list of all categories and their groups.

Thanks

**Comment by axtheset** [comment]
Thanks @yaseentt we'll have the team look into it.

**Comment by axtheset** [comment]
You should put 'group' and 'category' into request URL:
for example:
v4/records/DMEP-15PHS-00000-00341/documents?userId={userId}&category=AnimalPhoto&group=PHS&password={password}

**Comment by axtheset** [comment]
@yaseentt Did this work for you?

**Comment by yaseentt** [comment]
@axtheset Sorry I just got to try it out and it worked thanks a lot!
