### ISSUE TITLE
Issue getting inspections for a record

### ISSUE THREAD

**Issue by mmartin78** [Accela-Inc/developer-forum#54]
We have been trying to retrieve inspection records against two agencies and both requests fail with different errors. Please see below (this is all with a citizen app token):

**Do a search first:**

GET https://apis.accela.com/v4/records?limit=-1&offset=-1&customId=BB-201406683 HTTP/1.1
Content-Type: application/json
Accept: application/json
x-accela-appid: 635320897585197355
Authorization: <citizen-token>
x-accela-agency: ATLANTA_GA
x-accela-environment: PROD
Host: apis.accela.com

HTTP/1.1 200 OK

{"result":[{"name":"TERMINUS BUILDING ADDITION","id":"**ATLANTA_GA-14BLR-00000-20362**","type":{"module":"Building","type":"Commercial","value...

**Do a get inspection records, notice a not found error? but I just got that ID from the search:**

GET https://apis.accela.com/v4/records/ATLANTA_GA-14BLR-00000-20362/inspections?offset=0&limit=1000 HTTP/1.1
Content-Type: application/json
Accept: application/json
x-accela-appid: 635320897585197355
Authorization: <citizen-token>
x-accela-agency: ATLANTA_GA
x-accela-environment: PROD
Host: apis.accela.com

HTTP/1.1 400 Bad Request

{"status":400,"code":"data_validation_error","message":"The record ATLANTA_GA-14BLR-00000-20362 cannot be found.","traceId":"150129223454001-73a0b403"}

**Now we try against Palo Alto, and get different type of error 401, but the token is good:**

GET https://apis.accela.com/v4/records?limit=-1&offset=-1&customId=12000-02250 HTTP/1.1

HTTP/1.1 200 OK

{"result":[{"name":"CABACCAN","id":"PALOALTO-12000-00000-02250","type":{"module":"Building","type":"Project","value":"Building/Project/Building Permit/Building ...

GET https://apis.accela.com/v4/records/PALOALTO-12000-00000-02250/inspections?offset=0&limit=1000 HTTP/1.1

HTTP/1.1 401 Unauthorized

{"status":401,"code":"unauthorized","message":"Your session has expired.","traceId":"150129224110988...

**Comment by axtheset** [comment]
For your first test we will investigate the issue further.

For your second test it is a valid case that the agency does not expose inspections to the general public.  Inspection visibility can be configured for various levels, the record creator, a licensed professional on the record, a contact on the record, and all public users.  This will vary dependent on the requirements from the agency.

**Comment by mmartin78** [comment]
@axtheset thanks, that makes sense, but for the second case at the very least the error message is misleading **"message":"Your session has expired."**...

**Comment by axtheset** [comment]
Thanks for pointing that out, we'll investigate that as well.

**Comment by mmartin78** [comment]
@axtheset one question related to this. For example, for Atlanta, if we go through ACA we can see all the inspection information without logging in. However, calls to return the same type of information through the API return a 401 even with a valid token. Is there a correlation between what you see in ACA and the API permissions?
