### ISSUE TITLE
/v4/settings/records/types does not return all record types for agency

### ISSUE THREAD

**Issue by mmartin78** [Accela-Inc/developer-forum#55]
We invoke:

GET https://apis.accela.com/v4/settings/records/types?module=Building&offset=0&limit=1000 HTTP/1.1
Content-Type: application/json
Accept: application/json
x-accela-appid: 635320897585197355
x-accela-agency: ATLANTA_GA
x-accela-environment: PROD
Host: apis.accela.com

And it only returns 14 record types, why? However see ACA shows a lot more to filter the search.
https://aca.accela.com/Atlanta_ga/default.aspx

HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 4337
Content-Type: application/json
Expires: -1
Server: Microsoft-IIS/8.5
Server: Microsoft-IIS/7.5
Server: unknow
x-accela-resp-gateway-version: 3.1.0.1
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
x-accela-traceId: 150203033555886-2cf4edb1
X-Powered-By: ASP.NET
Date: Tue, 03 Feb 2015 03:35:56 GMT
Connection: close

{"result":[{"type":"Arborist","value":"Building/Arborist/Complaint/NA","category":"NA","text":"Arborist Complaint","group":"Building","module":"Building","subType":"Complaint","id":"Building-Arborist-Complaint-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Arborist","value":"Building/Arborist/Dead Dying Hazardous/NA","category":"NA","text":"Arborist Dead Dying Hazardous Tree","group":"Building","module":"Building","subType":"Dead Dying Hazardous","id":"Building-Arborist-Dead.cDying.cHazardous-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Arborist","value":"Building/Arborist/Plan Review/NA","category":"NA","text":"Building/Arborist/Plan Review/NA","group":"Building","module":"Building","subType":"Plan Review","id":"Building-Arborist-Plan.cReview-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Commercial","value":"Building/Commercial/Alteration/NA","category":"NA","text":"Commercial Alteration","group":"Building","module":"Building","subType":"Alteration","id":"Building-Commercial-Alteration-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Commercial","value":"Building/Commercial/Electrical/NA","category":"NA","text":"Electrical Commercial","group":"Building","module":"Building","subType":"Electrical","id":"Building-Commercial-Electrical-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Commercial","value":"Building/Commercial/HVAC/NA","category":"NA","text":"HVAC Commercial","group":"Building","module":"Building","subType":"HVAC","id":"Building-Commercial-HVAC-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Commercial","value":"Building/Commercial/Plumbing/NA","category":"NA","text":"Plumbing Commercial","group":"Building","module":"Building","subType":"Plumbing","id":"Building-Commercial-Plumbing-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Residential","value":"Building/Residential/Electrical/NA","category":"NA","text":"Electrical Single Family/Duplex","group":"Building","module":"Building","subType":"Electrical","id":"Building-Residential-Electrical-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Residential","value":"Building/Residential/Fire Sprinkler/NA","category":"NA","text":"Fire Sprinkler Single Family/Duplex","group":"Building","module":"Building","subType":"Fire Sprinkler","id":"Building-Residential-Fire.cSprinkler-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Residential","value":"Building/Residential/HVAC/NA","category":"NA","text":"HVAC Single Family/Duplex","group":"Building","module":"Building","subType":"HVAC","id":"Building-Residential-HVAC-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Residential","value":"Building/Residential/Low Voltage/NA","category":"NA","text":"Electrical Low Voltage Single Family/Duplex","group":"Building","module":"Building","subType":"Low Voltage","id":"Building-Residential-Low.cVoltage-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Residential","value":"Building/Residential/Plumbing/NA","category":"NA","text":"Plumbing Single Family/Duplex","group":"Building","module":"Building","subType":"Plumbing","id":"Building-Residential-Plumbing-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Residential","value":"Building/Residential/Repair/NA","category":"NA","text":"Single Family/Duplex Repair","group":"Building","module":"Building","subType":"Repair","id":"Building-Residential-Repair-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true},{"type":"Sign","value":"Building/Sign/Business/NA","category":"NA","text":"Sign Business","group":"Building","module":"Building","subType":"Business","id":"Building-Sign-Business-NA","readable":true,"createable":true,"updatable":true,"deletable":true,"searchable":true}],"page":{"offset":0,"limit":1000,"hasmore":false},"status":200}

**Comment by axtheset** [comment]
This are likely only 14 record types available to apply for online, you can search many more record types but only apply for 14.

**Comment by mmartin78** [comment]
How would I retrieve all record types then?

**Comment by axtheset** [comment]
Your only option would be with an agency token.
