### ISSUE TITLE
No ASI attributes in response while try to Get All Custom Form Settings for Contact Type

### ISSUE THREAD

**Issue by lalitgawad** [Accela-Inc/developer-forum#56]
While try to get All Custom Form Settings for Contact Type Individual, response just return HTTP 200 without any Contact ASI attributes. Contact type "Individual" has ASI associated with it.

See response below
{
"status": 200
}

Request: 
https://apis.accela.com/v4/settings/contacts/types/Individual/customForms

API SCOPE: get_settings_contact_type_customforms
API: /v4/settings/contacts/types/{id}/customForms?lang={lang}

**Comment by axtheset** [comment]
Thanks @lalitgawad we'll investigate and get back to you.

**Comment by axtheset** [comment]
@lalitgawad this API is retrieving people template data not generic template (ASI), I'll alert product to review this item.

**Comment by lalitgawad** [comment]
Ok. Since no people attributes created for Contact type "Individual", response just has success status.

**Comment by axtheset** [comment]
That is correct, the updated version will be in the next hotfix at the end of the month.
