### ISSUE TITLE
Searching Records Date Field Clarification

### ISSUE THREAD

**Issue by yaseentt** [Accela-Inc/developer-forum#57]
I'm trying to search a record by a Date Field, after much testing I managed to get it to work but I just want to confirm I'm doing it right.

The record has a date of 2015-02-08, when I search for that record I get the following result:

{
"Date of Occurrence": "2015-02-08"
}

If I send a search request using the following request:

{
"customForm": {"Date of Occurrence": "2015-02-08"}
}

I get no results, however after trying different things I managed to get it to work using the following request:

{
"customForm": {"Date of Occurrence": "02/08/2015"}
}

Is it a safe assumption that I can use mm/dd/yyyy for any type of date searching on Accela API? or is this configured someplace?

**Comment by axtheset** [comment]
Let me check on this for you.
