### ISSUE TITLE
POST /v4/search/records  >> 401

### ISSUE THREAD

**Issue by pedroqueiros** [Accela-Inc/developer-forum#59]
Hello,

I'm using /v4/search/records and based on the documentation, Authorization is not required:
https://developer.accela.com/docs/api_reference/v4.post.search.records.html

I've been using this method without the Authorization method successfully, but this weekend it stopped working and returns a 401. Did this change over the weekend? Is Authorization now required for this method?

X-Accela-Agency: ATLANTA_GA
X-Accela-Environment: PROD

Thank you,

**Comment by mheadd** [comment]
@pedroqueiros - looking into this issue and will have an update for you shortly.

**Comment by mheadd** [comment]
@pedroqueiros - there was an existing issue that our API team was investigating that is related to this. I've asked for a status update and hope to have that for you shortly.

**Comment by carterreece** [comment]
Any status update?

**Comment by mheadd** [comment]
@carterreece  This issue should be resolved in the next few days. Will update here when it is fixed.

**Comment by carterreece** [comment]
Still down, eh?

**Comment by pedroqueiros** [comment]
Yes, still getting 401 when calling this method :(

**Comment by axtheset** [comment]
We have received notice that a fix will be pushed to production this Thursday evening that will address this issue.

**Comment by axtheset** [comment]
@carterreece @pedroqueiros please give this another try and let us know if you are stilling having any issues.
