### ISSUE TITLE
Create Record Conditions - Http 400 > bad_request

### ISSUE THREAD

**Issue by lalitgawad** [Accela-Inc/developer-forum#60]
I am trying create condition on record as shown in following request which raises Http 400 > bad_request with message "Request type not match. Accept object type:java.util.List.".

Request Example=>
POST /v4/records/DEC-15DOC-00000-0000B/conditions HTTP/1.1
Host: apis.accela.com
Content-Type: application/json
Authorization: {token}
Accept: application/json

{ "statusType": "Applied", "shortComments": "Education for Ref Contact Updated", "longComments": "Long Comm", "type": { "value": "Fulfillment", "text": "Fulfillment" }, "group": { "value": "Fulfillment", "text": "Fulfillment"} }

**Comment by axtheset** [comment]
@lalitgawad I have opened a case for our team to investigate.  I should have more for you tomorrow.

**Comment by axtheset** [comment]
The request body should be an array, we'll get the documentation updated.

Also there are a few more required fields:

```json
[
  {
    "appliedbyDepartment": {
      "value": "DEC/ADMIN/NA/NA/NA/NA/NA"
    },
    "appliedbyUser": {
      "text": "ADMIN",
      "value": "ADMIN"
    },
    "statusType": "Applied",
    "name": "Education for Ref Contact Updated",
    "longComments": "Long Comm",
    "type": {
      "value": "Fulfillment",
      "text": "Fulfillment"
    },
    "group": {
      "value": "Fulfillment",
      "text": "Fulfillment"
    }
  }
]
```

**Comment by lalitgawad** [comment]
Ok, it works
