### ISSUE TITLE
OAuth password flow does not seem to work with agency id

### ISSUE THREAD

**Issue by mmartin78** [Accela-Inc/developer-forum#62]
We try: 
POST https://apis.accela.com/oauth2/token

grant_type=password&client_id=<**our app id**>&client_secret=<**our app secret**>&username=mdeveloper&password=accela&scope=records&environment=TEST&agency_name=Islandton

And get:

HTTP/1.1 400 Bad Request
x-accela-resp-message: Invalid username or password.
x-accela-traceId: 150210215029350-563edd98
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Tue, 10 Feb 2015 21:50:29 GMT

{"error":"invalid_request","error_description":"Invalid username or password."}

Isn't this supposed to work?

**Comment by axtheset** [comment]
Close but you need to a different content type:

POST /oauth2/token HTTP/1.1
Host: apis.accela.com
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

client_id=[app_id]&client_secret=[app_secret]&grant_type=password&username=mdeveloper&password=accela&scope=records&agency_name=ISLANDTON&environment=SUPP

**Comment by mmartin78** [comment]
I was actually using the wrong type of APPID, user error. Thanks!
