### ISSUE TITLE
REST API gap for ACA Announcements

### ISSUE THREAD

**Issue by lalitgawad** [Accela-Inc/developer-forum#63]
Hi,
 
Please see below issues/gaps found in REST API for Announcements in ACA.
 
Issue:
API for Get All Announcements returns response with only one. Token is created with Agency user credentials. 
 
Other  Questions/Issues:
1.	Is messages with AA only (Display Message In attribute) displays due to Agency user token according to recipient type?
 
2.	If “Display Message In attribute” is ACA then, announcement should display for public user with use role registered, Authorized Agent, Authorized Agent Clerk. Is this correct or we have gap?
 
3.	Not able to locate REST API to do new announcement “Mark as Read”
 
API: /v4/announcements?fields={fields}&lang={lang}
API Scope: get_announcements
Method: GET
 
Request:
GET /v4/announcements HTTP/1.1
Host: apis.accela.com
Content-Type: application/json
Authorization: {token}
Cache-Control: no-cache
 
Response:
{
    "result": [
        {
            "id": 1227,
            "text": "PUT MESSAGE HERE",
            "title": "TEST",
            "startEffectDate": "2014-04-11 00:00:00"
        }
    ],
    "status": 200
}

**Comment by axtheset** [comment]
Thanks @lalitgawad, we'll work with our product team to review this request.
