### ISSUE TITLE
Issue with fields of Date type in ASI Table records

### ISSUE THREAD

**Issue by ontiverosoo** [Accela-Inc/developer-forum#64]
I am experiencing a problem with the fields of date type when adding/updating a record in the ASI Tables. The date is being sent with the format “MM/dd/yyyy” and Accela is saving it wrong. Please take a look at the examples:

Request Information (Json format):
                                                
[
       {
              "id":"VISITS",
              "rows":
                      [
                             {
                                    "id":null,
                                    "action":"add",
                                    "fields":
                                           {
                                                  "Paint Out":"UNCHECKED",
                                                  "Visit Date":"02/16/2015",
                                                  "Visit Time":"12:30 PM",
                                                  "Mulch Out":"UNCHECKED",
                                                  "Trash":"UNCHECKED",
                                                  "Location":"Delta",
                                                  "Used Electronics":"UNCHECKED",
                                                  "Tires - QTY":0,
                                                  "HHW":"UNCHECKED",
                                                  "Recycling":"UNCHECKED",
                                                  "Christmas Trees - QTY":1,
                                                  "Brush/Yard Waste":"UNCHECKED",
                                                  "Scrap Metal":"UNCHECKED"
                                           }
                             }
                      ]
       }
]

Code Reference:
string path = "/v4/records/15C02-00000-00046/customTables?lang=en_US";
await _sharedAccelaSDK.PutAsync(path, json);

Record in Accela (Red):

![issue with fields of date type](https://cloud.githubusercontent.com/assets/10067518/6221735/998ac836-b604-11e4-8877-dc03a0aa85e1.jpg)
 

Based on the format Accela is displaying, I tried to send it with a different format “dd/MM/yyyy” ("Visit Date":"16/02/2015"). But, Accela saved it as “02/04/2016” (Blue). I have tried many other formats and the result is the same. Could anybody please help me with the issue?

**Comment by axtheset** [comment]
@ontiverosoo we'll take a look and get back to you.

**Comment by axtheset** [comment]
The following two formats will work for entering your date:
* 02-17-2015
* 2015-02-18

When using the forward slash the date will not be parsed correctly.
