### ISSUE TITLE
Create Related Details for Record raises HTTP 400  

### ISSUE THREAD

**Issue by lalitgawad** [Accela-Inc/developer-forum#65]
While creating related details for the record, I am getting HTTP 400: Request body is required
Also, how to create relationship while creating related details? 

Please see below additional information.
API Scope: create_record_related
URL: https://apis.accela.com/v4/records/{recordId}/related?lang={lang}

Request=>
POST /v4/records/DEC-15DOC-00000-0000O/related HTTP/1.1
Host: apis.accela.com
Content-Type: application/json
Authorization: {token}
Cache-Control: no-cache
{ "recordId": "DEC-15CAP-00000-0000O", "relatedRecordIds" : [{"DEC-15CAP-00000-00003"}] }

Response=>
{
    "status": 400,
    "code": "bad_request",
    "message": "Request body is required.",
    "traceId": "150217194537958-a6875d66"
}

**Comment by axtheset** [comment]
@lalitgawad the request body should actually be an array of strings.  So it would look like this:
```json
[ "DEC-15CAP-00000-00003" ]
```

**Comment by lalitgawad** [comment]
Worked after request body changes as explained.
