### ISSUE TITLE
Finalize Record raises - HTTP 400

### ISSUE THREAD

**Issue by lalitgawad** [Accela-Inc/developer-forum#66]
Finalize Record raises - HTTP 400 error with message Invalid Next Masked Sequence Parameters.
Please see additional information below.

API Scope: finalize_record
URL: https://apis.accela.com/v4/records/{recordId}/finalize?lang={lang}
HTTP Method: GET

Request=>
POST /v4/records/DEC-15ESZ-00000-0009H/finalize HTTP/1.1
Host: apis.accela.com
Content-Type: application/json
Authorization: {token}
Cache-Control: no-cache

{ "description": "", "status": { "value": "Approved", "text": "Approved" }, "statusDate": "2015-02-04 17:20:03", "renewalInfo": { "expirationDate": "2015-08-31 00:00:00" } } 

Response=>
{
    "status": 400,
    "code": "bad_request",
    "message": "Invalid Next Masked Sequence Parameters",
    "traceId": "150217201952966-0daf25d1"
}

**Comment by axtheset** [comment]
Did you submit a partial previously?  You may want to submit an empty request body.

**Comment by lalitgawad** [comment]
Yes, partial record was created before, Which returns "id":"DEC-15ESZ-00000-0009H". This id, i used in current request.

**Comment by axtheset** [comment]
Try submitting with a request body of {}

**Comment by lalitgawad** [comment]
With {} also gives error "Invalid Next Masked Sequence Parameters". 
But when i tried wit empty request body (No {} brackets) works.

**Comment by axtheset** [comment]
Ok, that's its intended use is to convert the partial to a full record.

**Comment by lalitgawad** [comment]
Now question is how to use Request Information provided in reference document? or it's not possible?

**Comment by axtheset** [comment]
You'll want to use create partial, update record (or custom forms, add contacts, etc..) for any updates along the way, and then finalize record.

**Comment by lalitgawad** [comment]
OK, thank you.
