### ISSUE TITLE
SDK Login and Environment name

### ISSUE THREAD

**Issue by citygovapp** [Accela-Inc/developer-forum#67]
We are using following call of SDK for login, this call presents a view in which user provide username, password and select environment. Our question is how we can know that, which environment is selected by user?
 
SDK Login Call
- (void)authorize2:(NSArray *) permissions withAgency:(NSString *) agency
 
In Session Delegate Handler, when we tried to get value of 'amEnvironmentType', it always returns zero.
-(void)amDidLogin:(int)grantType
{
ENVIRONMENT_TYPE environmentType = [self.accelaMobileamEnvironmentType];
    NSLog(@"Selected Environment: %d", environmentType);
}

**Comment by axtheset** [comment]
@citygovapp we'll get you feedback on this shortly.

**Comment by axtheset** [comment]
@citygovapp there is a request that will provide is

GET /oauth2/tokenInfo HTTP/1.1
Host: apis.accela.com
Authorization: [Token]
Cache-Control: no-cache

```json
{
    "appId": "31897987129837192873",
    "userId": "05ebf550-3d61-4eba-9828-09489cc6d45c",
    "agencyName": "ISLANDTON",
    "environment": "SUPP",
    "scopes": [
        "get_civicid_profile",
        "records"
    ],
    "expiresIn": 84664
}
```
