### ISSUE TITLE
Update Custom Table for Contact - HTTP 500

### ISSUE THREAD

**Issue by lalitgawad** [Accela-Inc/developer-forum#68]
While updating custom table for contact internal_server_error is occurred. Issue is the with body. Request body is missing Audit trail action. 

Please let us know what will be audit trail actions to update/delete/insert row.

API Scope: update_contact_customtables
HTTP Method: PUT

Request Example=>
PUT /v4/contacts/253380001608/customTables HTTP/1.1
Host: apis.accela.com
Content-Type: application/json
Authorization: {token}
Cache-Control: no-cache
[ { "id": "ASIT_APPLCNT-SPORTSMAN.cEDUCATION", "rows": [ { "id": "1", "fields": { "Sportsman Education Type": "Waterfowl", "State": "NY", "Certificate Number": "W-000431", "Revoked": "UNCHECKED", "Other Country": null, "Last Date": null, "Certification Date": "10/12/1989", "Country": "US" } }, { "id": "2", "fields": { "Sportsman Education Type": "Bowhunter Ed (IBEP)", "State": "NY", "Certificate Number": "BA102002", "Revoked": "UNCHECKED", "Other Country": null, "Last Date": null, "Certification Date": "10/16/2012", "Country": "US" } }, { "id": "3", "fields": { "Sportsman Education Type": "Trapper Ed", "State": "NY", "Certificate Number": "T-009721", "Revoked": null, "Other Country": null, "Last Date": null, "Certification Date": "06/19/2010", "Country": "US" } } ] } ] 

Response=>
{
    "status": 500,
    "code": "internal_server_error",
    "traceId": "150303204802454-70b906b3",
    "result": [
        {
            "id": "ASIT_APPLCNT-SPORTSMAN.cEDUCATION",
            "code": "data_validation_error",
            "message": "The custom table 'ASIT_APPLCNT-SPORTSMAN.cEDUCATION' row '1' action is required.",
            "isSuccess": false
        }
    ]
}

Message in server log file=>
The custom table 'ASIT_APPLCNT-SPORTSMAN.cEDUCATION' row '1' action is required.

**Comment by axtheset** [comment]
@lalitgawad it looks like you are missing the row.action, this needs to be add, update or delete.  If it is update or delete you will need to make sure you include row.id as well.

```json
[
   {
      "id": "ASIT_APPLCNT-SPORTSMAN.cEDUCATION",
      "rows": [
         {
            "action": "add",
            "fields": {
               "Sportsman Education Type": "Waterfowl",
               "State": "NY",
               "Certificate Number": "W-000431",
               "Revoked": "UNCHECKED",
               "Other Country": null,
               "Last Date": null,
               "Certification Date": "10/12/1989",
               "Country": "US"
            }
         },
         {
            "action": "add",
            "fields": {
               "Sportsman Education Type": "Bowhunter Ed (IBEP)",
               "State": "NY",
               "Certificate Number": "BA102002",
               "Revoked": "UNCHECKED",
               "Other Country": null,
               "Last Date": null,
               "Certification Date": "10/16/2012",
               "Country": "US"
            }
         },
         {
            "action": "add",
            "fields": {
               "Sportsman Education Type": "Trapper Ed",
               "State": "NY",
               "Certificate Number": "T-009721",
               "Revoked": null,
               "Other Country": null,
               "Last Date": null,
               "Certification Date": "06/19/2010",
               "Country": "US"
            }
         }
      ]
   }
]
```

**Comment by lalitgawad** [comment]
After adding audit trail actions, it’s working now.
