### ISSUE TITLE
Create Related Details for Record - HTTP 400 >> bad_request

### ISSUE THREAD

**Issue by lalitgawad** [Accela-Inc/developer-forum#69]
Causing HTTP 400 >> bad_request >> "Request body is required" exception with following request

API Scope: create_record_related
HTTP Method: Post

Request=>
PUT /v4/records/DEC-15CAP-00000-00097/related HTTP/1.1
Host: apis.accela.com
Content-Type: application/json
Authorization: {token}
Cache-Control: no-cache

{ "recordId": "DEC-15CAP-00000-00097", "relatedRecordIds" : [{"DEC-14CAP-00000-0M5NL"},{"14CAP-00000-0M5NJ"} , {"14CAP-00000-1E0JJ"} ] }

Response=>
{
    "status": 400,
    "code": "bad_request",
    "message": "Request body is required.",
    "traceId": "150305213637124-2d5daf61"
}

**Comment by axtheset** [comment]
@lalitgawad take a look at #65 for the resolution, the array will look like this, an array of strings:

```json
"relatedRecordIds" : [ "DEC-14CAP-00000-0M5NL", "14CAP-00000-0M5NJ" , "14CAP-00000-1E0JJ" ] }
```

**Comment by lalitgawad** [comment]
Still bad_request, It was worked in past when I tested for #65

**Comment by axtheset** [comment]
The array is the only payload.  So this is all you submit in the request body:

```json
[ "DEC-14CAP-00000-0M5NL", "14CAP-00000-0M5NJ" , "14CAP-00000-1E0JJ" ] 
```

Request
POST /v4/records/DEC-15CAP-00000-00097/related HTTP/1.1  
Host: apis.accela.com  
Authorization: [Token]  
Content-Type: application/json  
Cache-Control: no-cache  
```json
["DEC-14CAP-00000-0M5NL","14CAP-00000-0M5NJ" ,"14CAP-00000-1E0JJ" ]
```

Response
```json
{
    "status": 200,
    "result": [
        {
            "id": "DEC-14CAP-00000-0M5NL"
        },
        {
            "id": "DEC-14CAP-00000-0M5NJ"
        },
        {
            "id": "DEC-14CAP-00000-1E0JJ"
        }
    ]
}
```

**Comment by lalitgawad** [comment]
Worked.
