### ISSUE TITLE
Search Records not returns as per request body (criteria)

### ISSUE THREAD

**Issue by lalitgawad** [Accela-Inc/developer-forum#71]
Search Records response for request body having status and contact (having referenceContactId and contact type) returns records for contact other than criteria.

Reference:
https://developer.accela.com/docs/api_reference/v4.post.search.records.html

API Scope: search_records
HTTP Method: POST 

Request Example:
POST /v4/search/records?limit=1000&expand=contacts HTTP/1.1
Host: apis.accela.com
Content-Type: application/json
Authorization: {Agency Token}
Cache-Control: no-cache

{ "contact":{ "referenceContactId":"268480001757", "type":{ "value":"Individual" } }, "status":{ "type":{ "value":"Active" } } }

**Comment by axtheset** [comment]
@lalitgawad I've opened a case with our API team to research.  I'll email you with the ID.
