### ISSUE TITLE
Get All Folder Groups and other documents methods

### ISSUE THREAD

**Issue by yaseentt** [Accela-Inc/developer-forum#73]
I'm trying to get all document groups that I have using:

<a href="https://developer.accela.com/docs/api_reference/v4.get.settings.documents.folderGroups.html">Get All Folder Groups</a>

But I'm getting no results, I tried using:

<a href="https://developer.accela.com/docs/api_reference/v4.get.settings.documents.categories.html">Get All Document Categories</a>

It returned all categories that I have on the backend, I then tried copying a group id and passed it to:

<a href="https://developer.accela.com/docs/api_reference/v4.get.settings.documents.folders.groupId.html">Get Folder Group</a>

But I got "code": "resource_not_found" error.

I feel I'm misunderstanding folder groups, are they the same as document groups? and if so how can I get those methods to work?

Thanks a lot!

**Comment by axtheset** [comment]
@yaseentt folder groups are called Virtual Folders in the Accela UI.  [Get folder groups](https://www.runscope.com/public/fbae94a3-9ad7-427f-93ad-02afc58da9c0/c89a4435-dbdb-4f54-8795-f345997535c7) will get the list of groups.

![accela_automation__rbizdomainedit_-_r0080-e](https://cloud.githubusercontent.com/assets/1944978/7413499/79493586-ef1a-11e4-8156-79b028f71242.png)
