### ISSUE TITLE
Example of doing a POST with construct

### ISSUE THREAD

**Issue by TonyCat** [Accela-Inc/developer-forum#74]
I can get information from the construct APIs but I'm unable to post anything. I keep getting a Bad Server error. The documentation online never really shows what is needed to do a post. Am I missing a header? I just want to verify that I can post using any API I figured contacts would be easy since there are no required fields.

xhr.open("POST", "https://apis.accela.com/v4/contacts");
	/// I think this is all the request headers I need????
	xhr.setRequestHeader("Accept","application/json");
	xhr.setRequestHeader("Authorization", mytoken); ///I pass in the token via a variable this is not the issue it works on get requests that require tokens
	xhr.setRequestHeader("x-accela-appid",myAppidNumber);
	xhr.setRequestHeader("x-accela-appsecret",myAppSecret);
	xhr.setRequestHeader("x-accela-environment","DEV");
	xhr.setRequestHeader("x-accela-agency",myAgency);
	xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
	xhr.setRequestHeader("Cache-Control","no-cache");

	 
	
	var testbody = {"email":"Tony@yahoo.com","individualOrOrganization":"individual","phone1":"5188675309","firstName":"TONY","lastName":"DCAT"};

	xhr.send(JSON.stringify(testbody)); 
///Does the body need to be stringified?? I tried with & without

	xhr.onload = function() {
		Ti.API.info('RAW =' + this.responseText);
		if (this.status == '200') {
			Ti.API.info('got my response, http status code ' + this.status);
			if (this.readyState == 4) {
				var response = JSON.parse(this.responseText);
				Ti.API.info('Response = ' + response);
			} else {
				alert('HTTP Ready State != 4');
			}
		} else {
			alert('HTTp Error Response Status Code = ' + this.status);
			Ti.API.error("Error =>" + this.response);
		}

	};

**Comment by axtheset** [comment]
@TonyCat a few items:
* Content-Type should be application/json
* The payload should be an array
* Once additional field is required the "type"

See the below sample of creating a contact, we are using a shared sandbox in this example:

https://www.runscope.com/radar/q0cjt4z4p5p7/d814d825-c34e-417e-91af-9ad410b9a173/history/2c31ea34-64be-44ca-bf95-a4c50e3bf310

Also, we are moving away from using github issues for questions, please submit additional questions to developersupport@accela.com and we will get you help via that channel.
