### ISSUE TITLE
Open data help

### ISSUE THREAD

**Issue by jjramirez** [Accela-Inc/developer-forum#75]
Hi @mheadd ,

I'm trying to set up a private dataset on CivicData.com from our Accela hosted instance. We are not ready to start fully using it but I am doing the technical homework to see how it works and show it to our staff. I went through the instructions found at https://accelaeng.atlassian.net/wiki/display/PPD/Publishing+a+Dataset+to+CivicData.com but I still do not see any data being moved to CivicData. I'd appreciate any help you can give and I apologize if this is not the forum for CivicData! 

Jose

**Comment by mheadd** [comment]
@jjramirez You can send a note to developersupport@accela.com to get assistance with any questions you might have.

**Comment by mheadd** [comment]
I've moved the details over to our new support environment.

You can get an account and follow it [here](https://acceladev.zendesk.com/agent/tickets/58).
